// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTARgLqQsvbxLnmmQhOf7JJ0T0uoUnCh4',
    appId: '1:75327258104:web:e828caaacbc001c7422a0d',
    messagingSenderId: '75327258104',
    projectId: 'studentdirectoryapp-e553f',
    authDomain: 'studentdirectoryapp-e553f.firebaseapp.com',
    storageBucket: 'studentdirectoryapp-e553f.firebasestorage.app',
    measurementId: 'G-4KZ60ZGMWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_kjlP5NSICHqCZBaNXnDe9II1NCwcRq8',
    appId: '1:75327258104:android:0fa94c3baf4e93c5422a0d',
    messagingSenderId: '75327258104',
    projectId: 'studentdirectoryapp-e553f',
    storageBucket: 'studentdirectoryapp-e553f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGk1dEVGt3yMzT9uqud5ipX50lmB6mTKs',
    appId: '1:75327258104:ios:2e5b32cd69a8736f422a0d',
    messagingSenderId: '75327258104',
    projectId: 'studentdirectoryapp-e553f',
    storageBucket: 'studentdirectoryapp-e553f.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGk1dEVGt3yMzT9uqud5ipX50lmB6mTKs',
    appId: '1:75327258104:ios:2e5b32cd69a8736f422a0d',
    messagingSenderId: '75327258104',
    projectId: 'studentdirectoryapp-e553f',
    storageBucket: 'studentdirectoryapp-e553f.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTARgLqQsvbxLnmmQhOf7JJ0T0uoUnCh4',
    appId: '1:75327258104:web:c29225fd422e5b6b422a0d',
    messagingSenderId: '75327258104',
    projectId: 'studentdirectoryapp-e553f',
    authDomain: 'studentdirectoryapp-e553f.firebaseapp.com',
    storageBucket: 'studentdirectoryapp-e553f.firebasestorage.app',
    measurementId: 'G-D4S549K3RV',
  );
}
